basePath: /v1
definitions:
  models.Error:
    properties:
      text:
        type: string
    type: object
  models.GetBalance:
    properties:
      balance:
        type: number
    type: object
  models.UserAddBalance:
    properties:
      add_balance:
        type: number
      id:
        type: string
    type: object
  models.UserReserveAmount:
    properties:
      id:
        type: string
      reserved_amount:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is solution iv avito backend intership 2022 by prr133f
  title: Avito Intership 2022 Solution API
  version: "1.0"
paths:
  /balance:
    put:
      consumes:
      - application/json
      description: Returns new balance of user
      parameters:
      - description: DTO for adding user balance
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/models.UserAddBalance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Add balance to user
      tags:
      - Balance
  /balance/{id}:
    get:
      consumes:
      - application/json
      description: Returns balance of user by id
      parameters:
      - description: uuid of user
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetBalance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get balance of user
      tags:
      - Balance
  /reserve:
    put:
      consumes:
      - application/json
      description: Reserves a part of user balance
      parameters:
      - description: DTO for reserving part of user balance
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/models.UserReserveAmount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Reserve part of user balance
      tags:
      - Balance
swagger: "2.0"
