basePath: /v1
definitions:
  models.AddBalance:
    properties:
      new_balance:
        type: number
    type: object
  models.Error:
    properties:
      text:
        type: string
    type: object
  models.GetBalance:
    properties:
      balance:
        type: number
    type: object
  models.MonthlyReport:
    properties:
      margin:
        type: number
      service_name:
        type: string
    type: object
  models.ReserveBalance:
    properties:
      reserved_balance:
        type: number
    type: object
  models.UserAddBalance:
    properties:
      add_balance:
        type: number
      id:
        type: string
    type: object
  models.UserCommitAmount:
    properties:
      commited_amount:
        type: number
      order_id:
        type: string
      service_id:
        type: string
      user_id:
        type: string
    type: object
  models.UserReserveAmount:
    properties:
      order_id:
        type: string
      reserved_amount:
        type: number
      service_id:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  models.UserRestoreReservedAmount:
    properties:
      order_id:
        type: string
      restored_amount:
        type: number
      service_id:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is solution iv avito backend intership 2022 by prr133f
  title: Avito Intership 2022 Solution API
  version: "1.0"
paths:
  /balance:
    put:
      consumes:
      - application/json
      description: Returns new balance of user
      parameters:
      - description: DTO for adding user balance
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/models.UserAddBalance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AddBalance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Add balance to user
      tags:
      - Balance
  /balance/{id}:
    get:
      consumes:
      - application/json
      description: Returns balance of user by id
      parameters:
      - description: uuid of user
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetBalance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get balance of user
      tags:
      - Balance
  /commit:
    put:
      consumes:
      - application/json
      description: Commites previous reserved amount
      parameters:
      - description: DTO for commiting amount
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/models.UserCommitAmount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReserveBalance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Commit reserved amount
      tags:
      - Balance
  /report/{date}:
    put:
      consumes:
      - application/json
      description: Returns monthly margin report
      parameters:
      - description: date in format YYYY-MM
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MonthlyReport'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get monthly report
      tags:
      - Report
  /reserve:
    put:
      consumes:
      - application/json
      description: Reserves a part of user balance
      parameters:
      - description: DTO for reserving part of user balance
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/models.UserReserveAmount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReserveBalance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Reserve part of user balance
      tags:
      - Balance
  /restore:
    put:
      consumes:
      - application/json
      description: Restores a part of reserved user balance
      parameters:
      - description: DTO for restoring part of reserved user balance
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/models.UserRestoreReservedAmount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetBalance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Restore part of reserved user balance
      tags:
      - Balance
swagger: "2.0"
